spring:
  thymeleaf:
    mode: LEGACYHTML5
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/simpledb?useSSL=false
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
